In [2]:
# From Python
# It requires OpenCV installed for Python
import sys
import cv2
import os
from sys import platform

# Remember to add your installation path here
# Option b
# If you run `make install` (default path is `/usr/local/python` for Ubuntu), you can also access the OpenPose/python module from there. This will install OpenPose and the python library at your desired installation path. Ensure that this is in your python path in order to use it.
sys.path.insert(0,r'/home/lingheng/openpose_python_lib/python/openpose') 

# Parameters for OpenPose. Take a look at C++ OpenPose example for meaning of components. Ensure all below are filled
try:
    from openpose import *
except:
    raise Exception('Error: OpenPose library could not be found. Did you enable `BUILD_PYTHON` in CMake and have this Python script in the right folder?')
params = dict()
params["logging_level"] = 3
params["output_resolution"] = "-1x-1"
params["net_resolution"] = "-1x368"
params["model_pose"] = "BODY_25"
params["alpha_pose"] = 0.6
params["scale_gap"] = 0.3
params["scale_number"] = 1
params["render_threshold"] = 0.05
# If GPU version is built, and multiple GPUs are available, set the ID here
params["num_gpu_start"] = 0
params["disable_blending"] = False
# Ensure you point to the correct path where models are located
params["default_model_folder"] = "/home/lingheng/openpose/models/"
# Construct OpenPose object allocates GPU memory
openpose = OpenPose(params)

In [3]:
image_num = 1
for i in range(image_num):
    # Read new image
    img = cv2.imread("/home/lingheng/openpose/examples/media/COCO_val2014_000000000192.jpg")
    #img = cv2.imread("/home/lingheng/cropped_frame.png")
    # Output keypoints and the image with the human skeleton blended on it
    keypoints, output_image = openpose.forward(img, True)
    # Print the human pose keypoints, i.e., a [#people x #keypoints x 3]-dimensional numpy object with the keypoints of all the people on that image
    print(keypoints)
    # Display the image
    cv2.imwrite('cropped_frame_result.png',output_image)
    cv2.waitKey(15)

[[[0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [4.7818686e+02 2.7064902e+02 8.0004317e-01]
  [5.0167984e+02 2.6683109e+02 7.8615862e-01]
  [5.0557257e+02 2.8631619e+02 4.1359499e-01]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [4.5605368e+02 2.7328052e+02 8.1177360e-01]
  [4.4161090e+02 3.0716888e+02 5.7765830e-01]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [4.7428540e+02 3.3856528e+02 8.4464729e-01]
  [4.8600995e+02 3.3856204e+02 8.0585402e-01]
  [4.8735986e+02 3.8683725e+02 8.0624342e-01]
  [4.9649222e+02 4.4296634e+02 8.5596478e-01]
  [4.6247903e+02 3.3857523e+02 7.3071110e-01]
  [4.6380844e+02 3.9203384e+02 8.5256362e-01]
  [4.6517609e+02 4.4815677e+02 8.0368519e-01]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [0.0000000e+00 0.0000000e+00 0.0000000e+00]
  [4.8732040e+02 2.4456870e+02 2.3870946e-01]
  [4.6514783e+02 2.4456361e+02 8.3356512e-01]
  [4.4687830e+02 4.4818283e+02 6.0361648e-01]
  [4.4946487e+02 4.5209204e+02 6.8886161e-01]
  [4.7293259e+02 4.5470789e+02 8.3